### ISSUE TITLE
'NoneType' object has no attribute 'get_contents' when using cached Loader

### ISSUE THREAD

**Issue by oko-x** [bittner/django-apptemplates#13]
Hi,

I switched to django cached Loader 

    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [
                os.path.join(BASE_DIR, 'project', 'templates'),
                os.path.join(BASE_DIR, 'templates'),
            ],
            'OPTIONS': {
                'context_processors': [
                    ...
                ],
                'loaders': [
                    ('django.template.loaders.cached.Loader', [
                        'apptemplates.Loader',
                        ...
                    ]),
                ],
            },
        },
    ]  

and this error occured:

    'NoneType' object has no attribute 'get_contents'
    Request Method:	GET
    Django Version:	1.10.7
    Exception Type:	AttributeError
    Exception Value:	
    'NoneType' object has no attribute 'get_contents'
    Exception Location:	/lib/python3.4/site-packages/django/template/loaders/cached.py in get_contents, line 28
    Python Executable:	/bin/python
    Python Version:	3.4.2
    
    Template error:
    In template /project/templates/template.html, error at line 1
       'NoneType' object has no attribute 'get_contents'   1 :  {% extends "core:base_site.html" %} 
       2 : {% load static i18n %}
       3 : 
       4 : {% block content %}
       5 :     <div class="container-fluid article">
    
    
    Traceback:
    
    File "/lib/python3.4/site-packages/django/core/handlers/exception.py" in inner
      42.             response = get_response(request)
    
    File "/lib/python3.4/site-packages/django/core/handlers/base.py" in _legacy_get_response
      249.             response = self._get_response(request)
    
    File "/lib/python3.4/site-packages/django/core/handlers/base.py" in _get_response
      217.                 response = self.process_exception_by_middleware(e, request)
    
    File "/lib/python3.4/site-packages/django/core/handlers/base.py" in _get_response
      215.                 response = response.render()
    
    File "/lib/python3.4/site-packages/django/template/response.py" in render
      109.             self.content = self.rendered_content
    
    File "/lib/python3.4/site-packages/django/template/response.py" in rendered_content
      86.         content = template.render(context, self._request)
    
    File "/lib/python3.4/site-packages/django/template/backends/django.py" in render
      66.             return self.template.render(context)
    
    File "/lib/python3.4/site-packages/django/template/base.py" in render
      208.                     return self._render(context)
    
    File "/lib/python3.4/site-packages/django/template/base.py" in _render
      199.         return self.nodelist.render(context)
    
    File "/lib/python3.4/site-packages/django/template/base.py" in render
      994.                 bit = node.render_annotated(context)
    
    File "/lib/python3.4/site-packages/django/template/base.py" in render_annotated
      961.             return self.render(context)
    
    File "/lib/python3.4/site-packages/django/template/loader_tags.py" in render
      152.         compiled_parent = self.get_parent(context)
    
    File "/lib/python3.4/site-packages/django/template/loader_tags.py" in get_parent
      149.         return self.find_template(parent, context)
    
    File "/lib/python3.4/site-packages/django/template/loader_tags.py" in find_template
      129.             template_name, skip=history,
    
    File "/lib/python3.4/site-packages/django/template/engine.py" in find_template
      134.                         name, template_dirs=dirs, skip=skip,
    
    File "/lib/python3.4/site-packages/django/template/loaders/cached.py" in get_template
      60.                 template_name, template_dirs, skip,
    
    File "/lib/python3.4/site-packages/django/template/loaders/base.py" in get_template
      38.                 contents = self.get_contents(origin)
    
    File "/lib/python3.4/site-packages/django/template/loaders/cached.py" in get_contents
      28.         return origin.loader.get_contents(origin)
    
    Exception Type: AttributeError at /oprava-microsoft-xbox-360/poskodenie-tekutinou/
    Exception Value: 'NoneType' object has no attribute 'get_contents'

**Comment by oko-x** [comment]
works on version 1.4
